language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
# command to install dependencies
install:
  - pip install pytest pytest-cov pytest-travis-fold codecov
# command to run tests
script: py.test --cov=.
after_success:
  codecov
notifications:
  irc:
    channels:
      - "irc.hackint.eu#voc-wok"
    use_notice: true
    skip_join: true
