language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
# command to install dependencies
install:
  - pip install --upgrade coveralls pytest pytest-cov pytest-travis-fold
# command to run tests
script: py.test --cov=.
after_success:
  coveralls
notifications:
  irc:
    channels:
      - "irc.hackint.eu#voc-wok"
    use_notice: true
    skip_join: true
