language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
# command to install dependencies
install:
  - pip install tox-travis codecov
# command to run tests
script: tox
after_success:
  codecov --file .tox/cov-*.xml
notifications:
  irc:
    channels:
      - "irc.hackint.eu#voc-wok"
    use_notice: true
    skip_join: true
